project_id = "project_id"
my-vpc-network = "my-first-vpc-network"
vm_instance = "my_test_vm_instance"
machine_type = "e2-medium"
region = "us-central1"
zone = "us-central1-a"
storage_class = "STANDARD"
credentials = "gcp_devops.json"
